import { useMemo, useState } from "react";

import {
  BellIcon,
  BookmarkIcon,
  BoxIcon,
  BriefcaseIcon,
  BugIcon,
  CalendarIcon,
  CameraIcon,
  CloudIcon,
  CodeIcon,
  CoffeeIcon,
  CompassIcon,
  CpuIcon,
  DatabaseIcon,
  FlagIcon,
  FlameIcon,
  FolderIcon,
  GamepadIcon,
  GlobeIcon,
  HeartIcon,
  HouseIcon,
  ImageIcon,
  LayersIcon,
  LeafIcon,
  LightbulbIcon,
  MailIcon,
  MapIcon,
  MegaphoneIcon,
  MoonIcon,
  MusicIcon,
  PaletteIcon,
  PenToolIcon,
  RocketIcon,
  SearchIcon,
  ShieldIcon,
  SparklesIcon,
  StarIcon,
  SunIcon,
  TerminalIcon,
  TrendingUpIcon,
  TruckIcon,
  UsersIcon,
  VideoIcon,
  WandIcon,
  WrenchIcon,
  ZapIcon,
} from "lucide-react";

import { cn } from "../../lib/utils";

/**
 * Le sélecteur d'icône d'espace, façon Arc (demande fondateur 29/07 : « on
 * lui propose très peu d'icônes, et celles-là n'ont aucun sens »).
 *
 * Deux onglets — Emoji et Icône — une recherche, et des catégories. La liste
 * d'emoji est embarquée plutôt que tirée d'une dépendance : elle tient en
 * quelques kilo-octets, se cherche en FRANÇAIS comme en anglais, et n'ajoute
 * ni paquet ni surface d'attaque. Les icônes viennent de lucide, déjà là.
 */

interface Entree {
  readonly valeur: string;
  readonly mots: string;
}

const EMOJI_CATEGORIES: ReadonlyArray<{
  readonly nom: string;
  readonly entrees: ReadonlyArray<Entree>;
}> = [
  {
    nom: "Visages",
    entrees: [
      { valeur: "😀", mots: "visage tête émotion humeur" },
      { valeur: "😃", mots: "visage tête émotion humeur" },
      { valeur: "😄", mots: "visage tête émotion humeur" },
      { valeur: "😁", mots: "visage tête émotion humeur" },
      { valeur: "😆", mots: "visage tête émotion humeur" },
      { valeur: "😅", mots: "visage tête émotion humeur" },
      { valeur: "🤣", mots: "visage tête émotion humeur" },
      { valeur: "😂", mots: "visage tête émotion humeur" },
      { valeur: "🙂", mots: "visage tête émotion humeur" },
      { valeur: "🙃", mots: "visage tête émotion humeur" },
      { valeur: "😉", mots: "visage tête émotion humeur" },
      { valeur: "😊", mots: "visage tête émotion humeur" },
      { valeur: "😇", mots: "visage tête émotion humeur" },
      { valeur: "🥰", mots: "visage tête émotion humeur" },
      { valeur: "😍", mots: "visage tête émotion humeur" },
      { valeur: "🤩", mots: "visage tête émotion humeur" },
      { valeur: "😘", mots: "visage tête émotion humeur" },
      { valeur: "😗", mots: "visage tête émotion humeur" },
      { valeur: "😚", mots: "visage tête émotion humeur" },
      { valeur: "😙", mots: "visage tête émotion humeur" },
      { valeur: "🥲", mots: "visage tête émotion humeur" },
      { valeur: "😋", mots: "visage tête émotion humeur" },
      { valeur: "😛", mots: "visage tête émotion humeur" },
      { valeur: "😜", mots: "visage tête émotion humeur" },
      { valeur: "🤪", mots: "visage tête émotion humeur" },
      { valeur: "😝", mots: "visage tête émotion humeur" },
      { valeur: "🤑", mots: "visage tête émotion humeur" },
      { valeur: "🤗", mots: "visage tête émotion humeur" },
      { valeur: "🤭", mots: "visage tête émotion humeur" },
      { valeur: "🤫", mots: "visage tête émotion humeur" },
      { valeur: "🤔", mots: "visage tête émotion humeur" },
      { valeur: "🤐", mots: "visage tête émotion humeur" },
      { valeur: "🤨", mots: "visage tête émotion humeur" },
      { valeur: "😐", mots: "visage tête émotion humeur" },
      { valeur: "😑", mots: "visage tête émotion humeur" },
      { valeur: "😶", mots: "visage tête émotion humeur" },
      { valeur: "😏", mots: "visage tête émotion humeur" },
      { valeur: "😒", mots: "visage tête émotion humeur" },
      { valeur: "🙄", mots: "visage tête émotion humeur" },
      { valeur: "😬", mots: "visage tête émotion humeur" },
      { valeur: "🤥", mots: "visage tête émotion humeur" },
      { valeur: "😌", mots: "visage tête émotion humeur" },
      { valeur: "😔", mots: "visage tête émotion humeur" },
      { valeur: "😪", mots: "visage tête émotion humeur" },
      { valeur: "🤤", mots: "visage tête émotion humeur" },
      { valeur: "😴", mots: "visage tête émotion humeur" },
      { valeur: "😷", mots: "visage tête émotion humeur" },
      { valeur: "🤒", mots: "visage tête émotion humeur" },
      { valeur: "🤕", mots: "visage tête émotion humeur" },
      { valeur: "🤢", mots: "visage tête émotion humeur" },
      { valeur: "🤮", mots: "visage tête émotion humeur" },
      { valeur: "🤧", mots: "visage tête émotion humeur" },
      { valeur: "🥵", mots: "visage tête émotion humeur" },
      { valeur: "🥶", mots: "visage tête émotion humeur" },
      { valeur: "🥴", mots: "visage tête émotion humeur" },
      { valeur: "😵", mots: "visage tête émotion humeur" },
      { valeur: "🤯", mots: "visage tête émotion humeur" },
      { valeur: "🤠", mots: "visage tête émotion humeur" },
      { valeur: "🥳", mots: "visage tête émotion humeur" },
      { valeur: "🥸", mots: "visage tête émotion humeur" },
      { valeur: "😎", mots: "visage tête émotion humeur" },
      { valeur: "🤓", mots: "visage tête émotion humeur" },
      { valeur: "🧐", mots: "visage tête émotion humeur" },
      { valeur: "😕", mots: "visage tête émotion humeur" },
      { valeur: "😟", mots: "visage tête émotion humeur" },
      { valeur: "🙁", mots: "visage tête émotion humeur" },
      { valeur: "😮", mots: "visage tête émotion humeur" },
      { valeur: "😯", mots: "visage tête émotion humeur" },
      { valeur: "😲", mots: "visage tête émotion humeur" },
      { valeur: "😳", mots: "visage tête émotion humeur" },
      { valeur: "🥺", mots: "visage tête émotion humeur" },
      { valeur: "😦", mots: "visage tête émotion humeur" },
      { valeur: "😧", mots: "visage tête émotion humeur" },
      { valeur: "😨", mots: "visage tête émotion humeur" },
      { valeur: "😰", mots: "visage tête émotion humeur" },
      { valeur: "😥", mots: "visage tête émotion humeur" },
      { valeur: "😢", mots: "visage tête émotion humeur" },
      { valeur: "😭", mots: "visage tête émotion humeur" },
      { valeur: "😱", mots: "visage tête émotion humeur" },
      { valeur: "😖", mots: "visage tête émotion humeur" },
      { valeur: "😣", mots: "visage tête émotion humeur" },
      { valeur: "😞", mots: "visage tête émotion humeur" },
      { valeur: "😓", mots: "visage tête émotion humeur" },
      { valeur: "😩", mots: "visage tête émotion humeur" },
      { valeur: "😫", mots: "visage tête émotion humeur" },
      { valeur: "🥱", mots: "visage tête émotion humeur" },
      { valeur: "😤", mots: "visage tête émotion humeur" },
      { valeur: "😡", mots: "visage tête émotion humeur" },
      { valeur: "😠", mots: "visage tête émotion humeur" },
      { valeur: "🤬", mots: "visage tête émotion humeur" },
      { valeur: "😈", mots: "visage tête émotion humeur" },
      { valeur: "👿", mots: "visage tête émotion humeur" },
      { valeur: "💀", mots: "visage tête émotion humeur" },
      { valeur: "💩", mots: "visage tête émotion humeur" },
      { valeur: "🤡", mots: "visage tête émotion humeur" },
      { valeur: "👻", mots: "visage tête émotion humeur" },
      { valeur: "👽", mots: "visage tête émotion humeur" },
      { valeur: "🤖", mots: "visage tête émotion humeur" },
    ],
  },
  {
    nom: "Gestes",
    entrees: [
      { valeur: "👋", mots: "main geste doigt" },
      { valeur: "🤚", mots: "main geste doigt" },
      { valeur: "✋", mots: "main geste doigt" },
      { valeur: "🖖", mots: "main geste doigt" },
      { valeur: "👌", mots: "main geste doigt" },
      { valeur: "🤌", mots: "main geste doigt" },
      { valeur: "🤏", mots: "main geste doigt" },
      { valeur: "🤞", mots: "main geste doigt" },
      { valeur: "🤟", mots: "main geste doigt" },
      { valeur: "🤘", mots: "main geste doigt" },
      { valeur: "🤙", mots: "main geste doigt" },
      { valeur: "👈", mots: "main geste doigt" },
      { valeur: "👉", mots: "main geste doigt" },
      { valeur: "👆", mots: "main geste doigt" },
      { valeur: "👇", mots: "main geste doigt" },
      { valeur: "👍", mots: "main geste doigt" },
      { valeur: "👎", mots: "main geste doigt" },
      { valeur: "✊", mots: "main geste doigt" },
      { valeur: "👊", mots: "main geste doigt" },
      { valeur: "🤛", mots: "main geste doigt" },
      { valeur: "🤜", mots: "main geste doigt" },
      { valeur: "👏", mots: "main geste doigt" },
      { valeur: "🙌", mots: "main geste doigt" },
      { valeur: "🫶", mots: "main geste doigt" },
      { valeur: "👐", mots: "main geste doigt" },
      { valeur: "🤲", mots: "main geste doigt" },
      { valeur: "🤝", mots: "main geste doigt" },
      { valeur: "🙏", mots: "main geste doigt" },
      { valeur: "💅", mots: "main geste doigt" },
      { valeur: "🤳", mots: "main geste doigt" },
      { valeur: "💪", mots: "main geste doigt" },
      { valeur: "🦾", mots: "main geste doigt" },
      { valeur: "🦿", mots: "main geste doigt" },
      { valeur: "🦵", mots: "main geste doigt" },
      { valeur: "🦶", mots: "main geste doigt" },
      { valeur: "👂", mots: "main geste doigt" },
      { valeur: "🦻", mots: "main geste doigt" },
      { valeur: "👃", mots: "main geste doigt" },
      { valeur: "🧠", mots: "main geste doigt" },
      { valeur: "🫀", mots: "main geste doigt" },
      { valeur: "🫁", mots: "main geste doigt" },
      { valeur: "🦷", mots: "main geste doigt" },
      { valeur: "🦴", mots: "main geste doigt" },
      { valeur: "👀", mots: "main geste doigt" },
      { valeur: "👅", mots: "main geste doigt" },
      { valeur: "👄", mots: "main geste doigt" },
    ],
  },
  {
    nom: "Travail",
    entrees: [
      { valeur: "💼", mots: "travail bureau outil dev" },
      { valeur: "🏭", mots: "travail bureau outil dev" },
      { valeur: "🛠️", mots: "travail bureau outil dev" },
      { valeur: "⚙️", mots: "travail bureau outil dev" },
      { valeur: "📊", mots: "travail bureau outil dev" },
      { valeur: "📈", mots: "travail bureau outil dev" },
      { valeur: "📉", mots: "travail bureau outil dev" },
      { valeur: "🧪", mots: "travail bureau outil dev" },
      { valeur: "🐛", mots: "travail bureau outil dev" },
      { valeur: "🚀", mots: "travail bureau outil dev" },
      { valeur: "💡", mots: "travail bureau outil dev" },
      { valeur: "🎯", mots: "travail bureau outil dev" },
      { valeur: "📌", mots: "travail bureau outil dev" },
      { valeur: "🗂️", mots: "travail bureau outil dev" },
      { valeur: "📝", mots: "travail bureau outil dev" },
      { valeur: "🔍", mots: "travail bureau outil dev" },
      { valeur: "📋", mots: "travail bureau outil dev" },
      { valeur: "📎", mots: "travail bureau outil dev" },
      { valeur: "🖇️", mots: "travail bureau outil dev" },
      { valeur: "📁", mots: "travail bureau outil dev" },
      { valeur: "📂", mots: "travail bureau outil dev" },
      { valeur: "🗃️", mots: "travail bureau outil dev" },
      { valeur: "🗄️", mots: "travail bureau outil dev" },
      { valeur: "📅", mots: "travail bureau outil dev" },
      { valeur: "📆", mots: "travail bureau outil dev" },
      { valeur: "🗓️", mots: "travail bureau outil dev" },
      { valeur: "⏰", mots: "travail bureau outil dev" },
      { valeur: "⏱️", mots: "travail bureau outil dev" },
      { valeur: "⏲️", mots: "travail bureau outil dev" },
      { valeur: "💻", mots: "travail bureau outil dev" },
      { valeur: "🖥️", mots: "travail bureau outil dev" },
      { valeur: "⌨️", mots: "travail bureau outil dev" },
      { valeur: "🖱️", mots: "travail bureau outil dev" },
      { valeur: "🖨️", mots: "travail bureau outil dev" },
      { valeur: "💾", mots: "travail bureau outil dev" },
      { valeur: "💿", mots: "travail bureau outil dev" },
      { valeur: "📀", mots: "travail bureau outil dev" },
      { valeur: "🧮", mots: "travail bureau outil dev" },
      { valeur: "📱", mots: "travail bureau outil dev" },
      { valeur: "☎️", mots: "travail bureau outil dev" },
      { valeur: "📞", mots: "travail bureau outil dev" },
      { valeur: "📠", mots: "travail bureau outil dev" },
      { valeur: "🔌", mots: "travail bureau outil dev" },
      { valeur: "🔋", mots: "travail bureau outil dev" },
      { valeur: "🧰", mots: "travail bureau outil dev" },
      { valeur: "🔧", mots: "travail bureau outil dev" },
      { valeur: "🔨", mots: "travail bureau outil dev" },
      { valeur: "⛏️", mots: "travail bureau outil dev" },
      { valeur: "⚒️", mots: "travail bureau outil dev" },
      { valeur: "🗜️", mots: "travail bureau outil dev" },
      { valeur: "⚖️", mots: "travail bureau outil dev" },
      { valeur: "🔗", mots: "travail bureau outil dev" },
      { valeur: "⛓️", mots: "travail bureau outil dev" },
      { valeur: "🧲", mots: "travail bureau outil dev" },
    ],
  },
  {
    nom: "Création",
    entrees: [
      { valeur: "🎨", mots: "création design art musique" },
      { valeur: "✨", mots: "création design art musique" },
      { valeur: "🖌️", mots: "création design art musique" },
      { valeur: "🖼️", mots: "création design art musique" },
      { valeur: "🎬", mots: "création design art musique" },
      { valeur: "🎞️", mots: "création design art musique" },
      { valeur: "📽️", mots: "création design art musique" },
      { valeur: "🎧", mots: "création design art musique" },
      { valeur: "🎵", mots: "création design art musique" },
      { valeur: "🎶", mots: "création design art musique" },
      { valeur: "🎤", mots: "création design art musique" },
      { valeur: "🎸", mots: "création design art musique" },
      { valeur: "🎹", mots: "création design art musique" },
      { valeur: "🥁", mots: "création design art musique" },
      { valeur: "🎺", mots: "création design art musique" },
      { valeur: "🎷", mots: "création design art musique" },
      { valeur: "🪕", mots: "création design art musique" },
      { valeur: "🎻", mots: "création design art musique" },
      { valeur: "📷", mots: "création design art musique" },
      { valeur: "📸", mots: "création design art musique" },
      { valeur: "📹", mots: "création design art musique" },
      { valeur: "🎥", mots: "création design art musique" },
      { valeur: "🖊️", mots: "création design art musique" },
      { valeur: "🖋️", mots: "création design art musique" },
      { valeur: "✒️", mots: "création design art musique" },
      { valeur: "✏️", mots: "création design art musique" },
      { valeur: "📐", mots: "création design art musique" },
      { valeur: "📏", mots: "création design art musique" },
      { valeur: "🧵", mots: "création design art musique" },
      { valeur: "🧶", mots: "création design art musique" },
      { valeur: "🎭", mots: "création design art musique" },
      { valeur: "🎪", mots: "création design art musique" },
      { valeur: "🖍️", mots: "création design art musique" },
    ],
  },
  {
    nom: "Nature",
    entrees: [
      { valeur: "🌱", mots: "nature plante météo ciel" },
      { valeur: "🌿", mots: "nature plante météo ciel" },
      { valeur: "🍀", mots: "nature plante météo ciel" },
      { valeur: "🌵", mots: "nature plante météo ciel" },
      { valeur: "🌴", mots: "nature plante météo ciel" },
      { valeur: "🌳", mots: "nature plante météo ciel" },
      { valeur: "🌲", mots: "nature plante météo ciel" },
      { valeur: "🍂", mots: "nature plante météo ciel" },
      { valeur: "🍁", mots: "nature plante météo ciel" },
      { valeur: "🌾", mots: "nature plante météo ciel" },
      { valeur: "💐", mots: "nature plante météo ciel" },
      { valeur: "🌷", mots: "nature plante météo ciel" },
      { valeur: "🌹", mots: "nature plante météo ciel" },
      { valeur: "🥀", mots: "nature plante météo ciel" },
      { valeur: "🌺", mots: "nature plante météo ciel" },
      { valeur: "🌸", mots: "nature plante météo ciel" },
      { valeur: "🌼", mots: "nature plante météo ciel" },
      { valeur: "🌻", mots: "nature plante météo ciel" },
      { valeur: "🌞", mots: "nature plante météo ciel" },
      { valeur: "🌝", mots: "nature plante météo ciel" },
      { valeur: "🌚", mots: "nature plante météo ciel" },
      { valeur: "🌙", mots: "nature plante météo ciel" },
      { valeur: "⭐", mots: "nature plante météo ciel" },
      { valeur: "🌟", mots: "nature plante météo ciel" },
      { valeur: "💫", mots: "nature plante météo ciel" },
      { valeur: "☄️", mots: "nature plante météo ciel" },
      { valeur: "🌍", mots: "nature plante météo ciel" },
      { valeur: "🌎", mots: "nature plante météo ciel" },
      { valeur: "🌏", mots: "nature plante météo ciel" },
      { valeur: "🪐", mots: "nature plante météo ciel" },
      { valeur: "🔥", mots: "nature plante météo ciel" },
      { valeur: "💧", mots: "nature plante météo ciel" },
      { valeur: "🌊", mots: "nature plante météo ciel" },
      { valeur: "❄️", mots: "nature plante météo ciel" },
      { valeur: "⛄", mots: "nature plante météo ciel" },
      { valeur: "🌨️", mots: "nature plante météo ciel" },
      { valeur: "🌧️", mots: "nature plante météo ciel" },
      { valeur: "⛈️", mots: "nature plante météo ciel" },
      { valeur: "🌩️", mots: "nature plante météo ciel" },
      { valeur: "🌪️", mots: "nature plante météo ciel" },
      { valeur: "🌈", mots: "nature plante météo ciel" },
      { valeur: "☀️", mots: "nature plante météo ciel" },
      { valeur: "⛅", mots: "nature plante météo ciel" },
      { valeur: "☁️", mots: "nature plante météo ciel" },
      { valeur: "🌤️", mots: "nature plante météo ciel" },
    ],
  },
  {
    nom: "Animaux",
    entrees: [
      { valeur: "🐶", mots: "animal bête" },
      { valeur: "🐱", mots: "animal bête" },
      { valeur: "🐭", mots: "animal bête" },
      { valeur: "🐹", mots: "animal bête" },
      { valeur: "🐰", mots: "animal bête" },
      { valeur: "🦊", mots: "animal bête" },
      { valeur: "🐻", mots: "animal bête" },
      { valeur: "🐼", mots: "animal bête" },
      { valeur: "🐨", mots: "animal bête" },
      { valeur: "🐯", mots: "animal bête" },
      { valeur: "🦁", mots: "animal bête" },
      { valeur: "🐮", mots: "animal bête" },
      { valeur: "🐷", mots: "animal bête" },
      { valeur: "🐸", mots: "animal bête" },
      { valeur: "🐵", mots: "animal bête" },
      { valeur: "🙈", mots: "animal bête" },
      { valeur: "🙉", mots: "animal bête" },
      { valeur: "🙊", mots: "animal bête" },
      { valeur: "🐔", mots: "animal bête" },
      { valeur: "🐧", mots: "animal bête" },
      { valeur: "🐦", mots: "animal bête" },
      { valeur: "🐤", mots: "animal bête" },
      { valeur: "🦆", mots: "animal bête" },
      { valeur: "🦅", mots: "animal bête" },
      { valeur: "🦉", mots: "animal bête" },
      { valeur: "🦇", mots: "animal bête" },
      { valeur: "🐺", mots: "animal bête" },
      { valeur: "🐗", mots: "animal bête" },
      { valeur: "🐴", mots: "animal bête" },
      { valeur: "🦄", mots: "animal bête" },
      { valeur: "🐝", mots: "animal bête" },
      { valeur: "🦋", mots: "animal bête" },
      { valeur: "🐌", mots: "animal bête" },
      { valeur: "🐞", mots: "animal bête" },
      { valeur: "🐜", mots: "animal bête" },
      { valeur: "🕷️", mots: "animal bête" },
      { valeur: "🦂", mots: "animal bête" },
      { valeur: "🐢", mots: "animal bête" },
      { valeur: "🐍", mots: "animal bête" },
      { valeur: "🦎", mots: "animal bête" },
      { valeur: "🦖", mots: "animal bête" },
      { valeur: "🦕", mots: "animal bête" },
      { valeur: "🐙", mots: "animal bête" },
      { valeur: "🦑", mots: "animal bête" },
      { valeur: "🦐", mots: "animal bête" },
      { valeur: "🦀", mots: "animal bête" },
      { valeur: "🐡", mots: "animal bête" },
      { valeur: "🐠", mots: "animal bête" },
      { valeur: "🐟", mots: "animal bête" },
      { valeur: "🐬", mots: "animal bête" },
      { valeur: "🐳", mots: "animal bête" },
      { valeur: "🐋", mots: "animal bête" },
      { valeur: "🦈", mots: "animal bête" },
      { valeur: "🐊", mots: "animal bête" },
      { valeur: "🐅", mots: "animal bête" },
      { valeur: "🐆", mots: "animal bête" },
      { valeur: "🦓", mots: "animal bête" },
      { valeur: "🦍", mots: "animal bête" },
      { valeur: "🦧", mots: "animal bête" },
      { valeur: "🐘", mots: "animal bête" },
      { valeur: "🦛", mots: "animal bête" },
      { valeur: "🦏", mots: "animal bête" },
      { valeur: "🐪", mots: "animal bête" },
      { valeur: "🐫", mots: "animal bête" },
      { valeur: "🦒", mots: "animal bête" },
      { valeur: "🦘", mots: "animal bête" },
      { valeur: "🐃", mots: "animal bête" },
      { valeur: "🐂", mots: "animal bête" },
      { valeur: "🐄", mots: "animal bête" },
      { valeur: "🐎", mots: "animal bête" },
      { valeur: "🐖", mots: "animal bête" },
      { valeur: "🐏", mots: "animal bête" },
      { valeur: "🐑", mots: "animal bête" },
      { valeur: "🦙", mots: "animal bête" },
      { valeur: "🐐", mots: "animal bête" },
      { valeur: "🦌", mots: "animal bête" },
      { valeur: "🐕", mots: "animal bête" },
      { valeur: "🐩", mots: "animal bête" },
      { valeur: "🐈", mots: "animal bête" },
      { valeur: "🐓", mots: "animal bête" },
      { valeur: "🦃", mots: "animal bête" },
      { valeur: "🦚", mots: "animal bête" },
      { valeur: "🦜", mots: "animal bête" },
      { valeur: "🦢", mots: "animal bête" },
      { valeur: "🦩", mots: "animal bête" },
      { valeur: "🕊️", mots: "animal bête" },
      { valeur: "🐇", mots: "animal bête" },
      { valeur: "🦝", mots: "animal bête" },
      { valeur: "🦡", mots: "animal bête" },
      { valeur: "🦦", mots: "animal bête" },
      { valeur: "🦥", mots: "animal bête" },
      { valeur: "🐁", mots: "animal bête" },
      { valeur: "🐀", mots: "animal bête" },
      { valeur: "🐿️", mots: "animal bête" },
      { valeur: "🦔", mots: "animal bête" },
    ],
  },
  {
    nom: "Nourriture",
    entrees: [
      { valeur: "🍏", mots: "nourriture manger boire repas" },
      { valeur: "🍎", mots: "nourriture manger boire repas" },
      { valeur: "🍐", mots: "nourriture manger boire repas" },
      { valeur: "🍊", mots: "nourriture manger boire repas" },
      { valeur: "🍋", mots: "nourriture manger boire repas" },
      { valeur: "🍌", mots: "nourriture manger boire repas" },
      { valeur: "🍉", mots: "nourriture manger boire repas" },
      { valeur: "🍇", mots: "nourriture manger boire repas" },
      { valeur: "🍓", mots: "nourriture manger boire repas" },
      { valeur: "🍈", mots: "nourriture manger boire repas" },
      { valeur: "🍒", mots: "nourriture manger boire repas" },
      { valeur: "🍑", mots: "nourriture manger boire repas" },
      { valeur: "🥭", mots: "nourriture manger boire repas" },
      { valeur: "🍍", mots: "nourriture manger boire repas" },
      { valeur: "🥥", mots: "nourriture manger boire repas" },
      { valeur: "🥝", mots: "nourriture manger boire repas" },
      { valeur: "🍅", mots: "nourriture manger boire repas" },
      { valeur: "🍆", mots: "nourriture manger boire repas" },
      { valeur: "🥑", mots: "nourriture manger boire repas" },
      { valeur: "🥦", mots: "nourriture manger boire repas" },
      { valeur: "🥬", mots: "nourriture manger boire repas" },
      { valeur: "🥒", mots: "nourriture manger boire repas" },
      { valeur: "🌶️", mots: "nourriture manger boire repas" },
      { valeur: "🌽", mots: "nourriture manger boire repas" },
      { valeur: "🥕", mots: "nourriture manger boire repas" },
      { valeur: "🧄", mots: "nourriture manger boire repas" },
      { valeur: "🧅", mots: "nourriture manger boire repas" },
      { valeur: "🥔", mots: "nourriture manger boire repas" },
      { valeur: "🍠", mots: "nourriture manger boire repas" },
      { valeur: "🥐", mots: "nourriture manger boire repas" },
      { valeur: "🥯", mots: "nourriture manger boire repas" },
      { valeur: "🍞", mots: "nourriture manger boire repas" },
      { valeur: "🥖", mots: "nourriture manger boire repas" },
      { valeur: "🥨", mots: "nourriture manger boire repas" },
      { valeur: "🧀", mots: "nourriture manger boire repas" },
      { valeur: "🥚", mots: "nourriture manger boire repas" },
      { valeur: "🍳", mots: "nourriture manger boire repas" },
      { valeur: "🥞", mots: "nourriture manger boire repas" },
      { valeur: "🧇", mots: "nourriture manger boire repas" },
      { valeur: "🥓", mots: "nourriture manger boire repas" },
      { valeur: "🥩", mots: "nourriture manger boire repas" },
      { valeur: "🍗", mots: "nourriture manger boire repas" },
      { valeur: "🍖", mots: "nourriture manger boire repas" },
      { valeur: "🌭", mots: "nourriture manger boire repas" },
      { valeur: "🍔", mots: "nourriture manger boire repas" },
      { valeur: "🍟", mots: "nourriture manger boire repas" },
      { valeur: "🍕", mots: "nourriture manger boire repas" },
      { valeur: "🥪", mots: "nourriture manger boire repas" },
      { valeur: "🌮", mots: "nourriture manger boire repas" },
      { valeur: "🌯", mots: "nourriture manger boire repas" },
      { valeur: "🥙", mots: "nourriture manger boire repas" },
      { valeur: "🥘", mots: "nourriture manger boire repas" },
      { valeur: "🍲", mots: "nourriture manger boire repas" },
      { valeur: "🍜", mots: "nourriture manger boire repas" },
      { valeur: "🍝", mots: "nourriture manger boire repas" },
      { valeur: "🍢", mots: "nourriture manger boire repas" },
      { valeur: "🍣", mots: "nourriture manger boire repas" },
      { valeur: "🍤", mots: "nourriture manger boire repas" },
      { valeur: "🍥", mots: "nourriture manger boire repas" },
      { valeur: "🍡", mots: "nourriture manger boire repas" },
      { valeur: "🥟", mots: "nourriture manger boire repas" },
      { valeur: "🥠", mots: "nourriture manger boire repas" },
      { valeur: "🥡", mots: "nourriture manger boire repas" },
      { valeur: "☕", mots: "nourriture manger boire repas" },
      { valeur: "🍵", mots: "nourriture manger boire repas" },
      { valeur: "🥤", mots: "nourriture manger boire repas" },
      { valeur: "🍺", mots: "nourriture manger boire repas" },
      { valeur: "🍻", mots: "nourriture manger boire repas" },
      { valeur: "🥂", mots: "nourriture manger boire repas" },
      { valeur: "🍷", mots: "nourriture manger boire repas" },
      { valeur: "🥃", mots: "nourriture manger boire repas" },
      { valeur: "🍸", mots: "nourriture manger boire repas" },
      { valeur: "🍹", mots: "nourriture manger boire repas" },
      { valeur: "🍾", mots: "nourriture manger boire repas" },
      { valeur: "🧊", mots: "nourriture manger boire repas" },
      { valeur: "🥄", mots: "nourriture manger boire repas" },
      { valeur: "🍴", mots: "nourriture manger boire repas" },
      { valeur: "🍽️", mots: "nourriture manger boire repas" },
    ],
  },
  {
    nom: "Voyage",
    entrees: [
      { valeur: "🚗", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚕", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚙", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚌", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏎️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚓", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚑", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚒", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚐", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚚", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚛", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚜", mots: "voyage transport lieu bâtiment" },
      { valeur: "🛴", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚲", mots: "voyage transport lieu bâtiment" },
      { valeur: "🛵", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏍️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚨", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚔", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚘", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚖", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚡", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚠", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚃", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚋", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚞", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚝", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚄", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚅", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚈", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚂", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚆", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚇", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚊", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚉", mots: "voyage transport lieu bâtiment" },
      { valeur: "✈️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🛫", mots: "voyage transport lieu bâtiment" },
      { valeur: "🛬", mots: "voyage transport lieu bâtiment" },
      { valeur: "🛩️", mots: "voyage transport lieu bâtiment" },
      { valeur: "💺", mots: "voyage transport lieu bâtiment" },
      { valeur: "🛰️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🛸", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚁", mots: "voyage transport lieu bâtiment" },
      { valeur: "🛶", mots: "voyage transport lieu bâtiment" },
      { valeur: "⛵", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚤", mots: "voyage transport lieu bâtiment" },
      { valeur: "🛥️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🛳️", mots: "voyage transport lieu bâtiment" },
      { valeur: "⛴️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚢", mots: "voyage transport lieu bâtiment" },
      { valeur: "⚓", mots: "voyage transport lieu bâtiment" },
      { valeur: "⛽", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚧", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚦", mots: "voyage transport lieu bâtiment" },
      { valeur: "🚥", mots: "voyage transport lieu bâtiment" },
      { valeur: "🗺️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🗿", mots: "voyage transport lieu bâtiment" },
      { valeur: "🗽", mots: "voyage transport lieu bâtiment" },
      { valeur: "🗼", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏰", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏯", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏟️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🎡", mots: "voyage transport lieu bâtiment" },
      { valeur: "🎢", mots: "voyage transport lieu bâtiment" },
      { valeur: "🎠", mots: "voyage transport lieu bâtiment" },
      { valeur: "⛲", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏖️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏝️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏜️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🌋", mots: "voyage transport lieu bâtiment" },
      { valeur: "⛰️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏔️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🗻", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏕️", mots: "voyage transport lieu bâtiment" },
      { valeur: "⛺", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏠", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏡", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏘️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏗️", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏢", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏬", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏣", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏥", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏦", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏨", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏪", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏫", mots: "voyage transport lieu bâtiment" },
      { valeur: "🏛️", mots: "voyage transport lieu bâtiment" },
      { valeur: "⛪", mots: "voyage transport lieu bâtiment" },
    ],
  },
  {
    nom: "Sport",
    entrees: [
      { valeur: "⚽", mots: "sport jeu loisir" },
      { valeur: "🏀", mots: "sport jeu loisir" },
      { valeur: "🏈", mots: "sport jeu loisir" },
      { valeur: "⚾", mots: "sport jeu loisir" },
      { valeur: "🎾", mots: "sport jeu loisir" },
      { valeur: "🏐", mots: "sport jeu loisir" },
      { valeur: "🏉", mots: "sport jeu loisir" },
      { valeur: "🎱", mots: "sport jeu loisir" },
      { valeur: "🏓", mots: "sport jeu loisir" },
      { valeur: "🏸", mots: "sport jeu loisir" },
      { valeur: "🏒", mots: "sport jeu loisir" },
      { valeur: "🏑", mots: "sport jeu loisir" },
      { valeur: "🏏", mots: "sport jeu loisir" },
      { valeur: "🥅", mots: "sport jeu loisir" },
      { valeur: "⛳", mots: "sport jeu loisir" },
      { valeur: "🏹", mots: "sport jeu loisir" },
      { valeur: "🎣", mots: "sport jeu loisir" },
      { valeur: "🥊", mots: "sport jeu loisir" },
      { valeur: "🥋", mots: "sport jeu loisir" },
      { valeur: "🎽", mots: "sport jeu loisir" },
      { valeur: "🛹", mots: "sport jeu loisir" },
      { valeur: "🛼", mots: "sport jeu loisir" },
      { valeur: "⛸️", mots: "sport jeu loisir" },
      { valeur: "🎿", mots: "sport jeu loisir" },
      { valeur: "⛷️", mots: "sport jeu loisir" },
      { valeur: "🏂", mots: "sport jeu loisir" },
      { valeur: "🏋️", mots: "sport jeu loisir" },
      { valeur: "🤸", mots: "sport jeu loisir" },
      { valeur: "⛹️", mots: "sport jeu loisir" },
      { valeur: "🏌️", mots: "sport jeu loisir" },
      { valeur: "🏇", mots: "sport jeu loisir" },
      { valeur: "🧘", mots: "sport jeu loisir" },
      { valeur: "🏄", mots: "sport jeu loisir" },
      { valeur: "🏊", mots: "sport jeu loisir" },
      { valeur: "🚣", mots: "sport jeu loisir" },
      { valeur: "🧗", mots: "sport jeu loisir" },
      { valeur: "🚵", mots: "sport jeu loisir" },
      { valeur: "🚴", mots: "sport jeu loisir" },
      { valeur: "🏆", mots: "sport jeu loisir" },
      { valeur: "🥇", mots: "sport jeu loisir" },
      { valeur: "🥈", mots: "sport jeu loisir" },
      { valeur: "🥉", mots: "sport jeu loisir" },
      { valeur: "🏅", mots: "sport jeu loisir" },
      { valeur: "🎖️", mots: "sport jeu loisir" },
      { valeur: "🎗️", mots: "sport jeu loisir" },
      { valeur: "🎫", mots: "sport jeu loisir" },
      { valeur: "🤹", mots: "sport jeu loisir" },
      { valeur: "🩰", mots: "sport jeu loisir" },
      { valeur: "🎼", mots: "sport jeu loisir" },
    ],
  },
  {
    nom: "Objets",
    entrees: [
      { valeur: "📦", mots: "objet chose matériel" },
      { valeur: "🎁", mots: "objet chose matériel" },
      { valeur: "🎀", mots: "objet chose matériel" },
      { valeur: "🎈", mots: "objet chose matériel" },
      { valeur: "🎉", mots: "objet chose matériel" },
      { valeur: "🎊", mots: "objet chose matériel" },
      { valeur: "🧧", mots: "objet chose matériel" },
      { valeur: "✉️", mots: "objet chose matériel" },
      { valeur: "📧", mots: "objet chose matériel" },
      { valeur: "📨", mots: "objet chose matériel" },
      { valeur: "📩", mots: "objet chose matériel" },
      { valeur: "📤", mots: "objet chose matériel" },
      { valeur: "📥", mots: "objet chose matériel" },
      { valeur: "📮", mots: "objet chose matériel" },
      { valeur: "🗳️", mots: "objet chose matériel" },
      { valeur: "📪", mots: "objet chose matériel" },
      { valeur: "📫", mots: "objet chose matériel" },
      { valeur: "📬", mots: "objet chose matériel" },
      { valeur: "📭", mots: "objet chose matériel" },
      { valeur: "📜", mots: "objet chose matériel" },
      { valeur: "📃", mots: "objet chose matériel" },
      { valeur: "📄", mots: "objet chose matériel" },
      { valeur: "📑", mots: "objet chose matériel" },
      { valeur: "🧾", mots: "objet chose matériel" },
      { valeur: "🗒️", mots: "objet chose matériel" },
      { valeur: "📓", mots: "objet chose matériel" },
      { valeur: "📔", mots: "objet chose matériel" },
      { valeur: "📒", mots: "objet chose matériel" },
      { valeur: "📕", mots: "objet chose matériel" },
      { valeur: "📗", mots: "objet chose matériel" },
      { valeur: "📘", mots: "objet chose matériel" },
      { valeur: "📙", mots: "objet chose matériel" },
      { valeur: "📚", mots: "objet chose matériel" },
      { valeur: "📖", mots: "objet chose matériel" },
      { valeur: "🔖", mots: "objet chose matériel" },
      { valeur: "🧷", mots: "objet chose matériel" },
      { valeur: "📰", mots: "objet chose matériel" },
      { valeur: "🗞️", mots: "objet chose matériel" },
      { valeur: "🔎", mots: "objet chose matériel" },
      { valeur: "🔬", mots: "objet chose matériel" },
      { valeur: "🔭", mots: "objet chose matériel" },
      { valeur: "📡", mots: "objet chose matériel" },
      { valeur: "💉", mots: "objet chose matériel" },
      { valeur: "💊", mots: "objet chose matériel" },
      { valeur: "🩹", mots: "objet chose matériel" },
      { valeur: "🩺", mots: "objet chose matériel" },
      { valeur: "🚪", mots: "objet chose matériel" },
      { valeur: "🪑", mots: "objet chose matériel" },
      { valeur: "🛏️", mots: "objet chose matériel" },
      { valeur: "🛋️", mots: "objet chose matériel" },
      { valeur: "🚿", mots: "objet chose matériel" },
      { valeur: "🛁", mots: "objet chose matériel" },
      { valeur: "🧴", mots: "objet chose matériel" },
      { valeur: "🧹", mots: "objet chose matériel" },
      { valeur: "🧺", mots: "objet chose matériel" },
      { valeur: "🧻", mots: "objet chose matériel" },
      { valeur: "🧼", mots: "objet chose matériel" },
      { valeur: "🧽", mots: "objet chose matériel" },
      { valeur: "🧯", mots: "objet chose matériel" },
      { valeur: "🛒", mots: "objet chose matériel" },
      { valeur: "⚰️", mots: "objet chose matériel" },
      { valeur: "🗝️", mots: "objet chose matériel" },
      { valeur: "🔑", mots: "objet chose matériel" },
      { valeur: "🔐", mots: "objet chose matériel" },
      { valeur: "🔒", mots: "objet chose matériel" },
      { valeur: "🔓", mots: "objet chose matériel" },
      { valeur: "🪓", mots: "objet chose matériel" },
      { valeur: "🛡️", mots: "objet chose matériel" },
      { valeur: "🔮", mots: "objet chose matériel" },
      { valeur: "🧿", mots: "objet chose matériel" },
      { valeur: "🎮", mots: "objet chose matériel" },
      { valeur: "🕹️", mots: "objet chose matériel" },
      { valeur: "🎰", mots: "objet chose matériel" },
      { valeur: "🎲", mots: "objet chose matériel" },
      { valeur: "🧩", mots: "objet chose matériel" },
      { valeur: "🧸", mots: "objet chose matériel" },
    ],
  },
  {
    nom: "Symboles",
    entrees: [
      { valeur: "❤️", mots: "symbole signe flèche forme" },
      { valeur: "🧡", mots: "symbole signe flèche forme" },
      { valeur: "💛", mots: "symbole signe flèche forme" },
      { valeur: "💚", mots: "symbole signe flèche forme" },
      { valeur: "💙", mots: "symbole signe flèche forme" },
      { valeur: "💜", mots: "symbole signe flèche forme" },
      { valeur: "🖤", mots: "symbole signe flèche forme" },
      { valeur: "🤍", mots: "symbole signe flèche forme" },
      { valeur: "🤎", mots: "symbole signe flèche forme" },
      { valeur: "💔", mots: "symbole signe flèche forme" },
      { valeur: "💕", mots: "symbole signe flèche forme" },
      { valeur: "💞", mots: "symbole signe flèche forme" },
      { valeur: "💓", mots: "symbole signe flèche forme" },
      { valeur: "💗", mots: "symbole signe flèche forme" },
      { valeur: "💖", mots: "symbole signe flèche forme" },
      { valeur: "💘", mots: "symbole signe flèche forme" },
      { valeur: "💝", mots: "symbole signe flèche forme" },
      { valeur: "☮️", mots: "symbole signe flèche forme" },
      { valeur: "✝️", mots: "symbole signe flèche forme" },
      { valeur: "☪️", mots: "symbole signe flèche forme" },
      { valeur: "🕉️", mots: "symbole signe flèche forme" },
      { valeur: "☸️", mots: "symbole signe flèche forme" },
      { valeur: "✡️", mots: "symbole signe flèche forme" },
      { valeur: "☯️", mots: "symbole signe flèche forme" },
      { valeur: "⛎", mots: "symbole signe flèche forme" },
      { valeur: "♈", mots: "symbole signe flèche forme" },
      { valeur: "♉", mots: "symbole signe flèche forme" },
      { valeur: "♊", mots: "symbole signe flèche forme" },
      { valeur: "♋", mots: "symbole signe flèche forme" },
      { valeur: "♌", mots: "symbole signe flèche forme" },
      { valeur: "♍", mots: "symbole signe flèche forme" },
      { valeur: "♎", mots: "symbole signe flèche forme" },
      { valeur: "♏", mots: "symbole signe flèche forme" },
      { valeur: "♐", mots: "symbole signe flèche forme" },
      { valeur: "♑", mots: "symbole signe flèche forme" },
      { valeur: "♒", mots: "symbole signe flèche forme" },
      { valeur: "♓", mots: "symbole signe flèche forme" },
      { valeur: "⚛️", mots: "symbole signe flèche forme" },
      { valeur: "☢️", mots: "symbole signe flèche forme" },
      { valeur: "☣️", mots: "symbole signe flèche forme" },
      { valeur: "✴️", mots: "symbole signe flèche forme" },
      { valeur: "🆚", mots: "symbole signe flèche forme" },
      { valeur: "💮", mots: "symbole signe flèche forme" },
      { valeur: "❌", mots: "symbole signe flèche forme" },
      { valeur: "⭕", mots: "symbole signe flèche forme" },
      { valeur: "🛑", mots: "symbole signe flèche forme" },
      { valeur: "⛔", mots: "symbole signe flèche forme" },
      { valeur: "📛", mots: "symbole signe flèche forme" },
      { valeur: "🚫", mots: "symbole signe flèche forme" },
      { valeur: "💯", mots: "symbole signe flèche forme" },
      { valeur: "💢", mots: "symbole signe flèche forme" },
      { valeur: "♨️", mots: "symbole signe flèche forme" },
      { valeur: "🔞", mots: "symbole signe flèche forme" },
      { valeur: "❗", mots: "symbole signe flèche forme" },
      { valeur: "❓", mots: "symbole signe flèche forme" },
      { valeur: "‼️", mots: "symbole signe flèche forme" },
      { valeur: "⁉️", mots: "symbole signe flèche forme" },
      { valeur: "🔅", mots: "symbole signe flèche forme" },
      { valeur: "🔆", mots: "symbole signe flèche forme" },
      { valeur: "⚠️", mots: "symbole signe flèche forme" },
      { valeur: "🔱", mots: "symbole signe flèche forme" },
      { valeur: "⚜️", mots: "symbole signe flèche forme" },
      { valeur: "🔰", mots: "symbole signe flèche forme" },
      { valeur: "♻️", mots: "symbole signe flèche forme" },
      { valeur: "✅", mots: "symbole signe flèche forme" },
      { valeur: "💹", mots: "symbole signe flèche forme" },
      { valeur: "❇️", mots: "symbole signe flèche forme" },
      { valeur: "✳️", mots: "symbole signe flèche forme" },
      { valeur: "🌐", mots: "symbole signe flèche forme" },
      { valeur: "💠", mots: "symbole signe flèche forme" },
      { valeur: "🌀", mots: "symbole signe flèche forme" },
      { valeur: "💤", mots: "symbole signe flèche forme" },
      { valeur: "♿", mots: "symbole signe flèche forme" },
      { valeur: "🅿️", mots: "symbole signe flèche forme" },
      { valeur: "🚹", mots: "symbole signe flèche forme" },
      { valeur: "🚺", mots: "symbole signe flèche forme" },
      { valeur: "🚻", mots: "symbole signe flèche forme" },
      { valeur: "🚮", mots: "symbole signe flèche forme" },
      { valeur: "📶", mots: "symbole signe flèche forme" },
      { valeur: "ℹ️", mots: "symbole signe flèche forme" },
      { valeur: "🔤", mots: "symbole signe flèche forme" },
      { valeur: "🔡", mots: "symbole signe flèche forme" },
      { valeur: "🔠", mots: "symbole signe flèche forme" },
      { valeur: "🆖", mots: "symbole signe flèche forme" },
      { valeur: "🆗", mots: "symbole signe flèche forme" },
      { valeur: "🆙", mots: "symbole signe flèche forme" },
      { valeur: "🆒", mots: "symbole signe flèche forme" },
      { valeur: "🆕", mots: "symbole signe flèche forme" },
      { valeur: "🆓", mots: "symbole signe flèche forme" },
      { valeur: "🔟", mots: "symbole signe flèche forme" },
      { valeur: "🔢", mots: "symbole signe flèche forme" },
      { valeur: "▶️", mots: "symbole signe flèche forme" },
      { valeur: "⏸️", mots: "symbole signe flèche forme" },
      { valeur: "⏹️", mots: "symbole signe flèche forme" },
      { valeur: "⏺️", mots: "symbole signe flèche forme" },
      { valeur: "⏭️", mots: "symbole signe flèche forme" },
      { valeur: "⏮️", mots: "symbole signe flèche forme" },
      { valeur: "⏩", mots: "symbole signe flèche forme" },
      { valeur: "⏪", mots: "symbole signe flèche forme" },
      { valeur: "◀️", mots: "symbole signe flèche forme" },
      { valeur: "🔼", mots: "symbole signe flèche forme" },
      { valeur: "🔽", mots: "symbole signe flèche forme" },
      { valeur: "➡️", mots: "symbole signe flèche forme" },
      { valeur: "⬅️", mots: "symbole signe flèche forme" },
      { valeur: "⬆️", mots: "symbole signe flèche forme" },
      { valeur: "⬇️", mots: "symbole signe flèche forme" },
      { valeur: "↗️", mots: "symbole signe flèche forme" },
      { valeur: "↘️", mots: "symbole signe flèche forme" },
      { valeur: "↙️", mots: "symbole signe flèche forme" },
      { valeur: "↖️", mots: "symbole signe flèche forme" },
      { valeur: "↕️", mots: "symbole signe flèche forme" },
      { valeur: "↔️", mots: "symbole signe flèche forme" },
      { valeur: "↪️", mots: "symbole signe flèche forme" },
      { valeur: "↩️", mots: "symbole signe flèche forme" },
      { valeur: "🔀", mots: "symbole signe flèche forme" },
      { valeur: "🔁", mots: "symbole signe flèche forme" },
      { valeur: "🔂", mots: "symbole signe flèche forme" },
      { valeur: "🔄", mots: "symbole signe flèche forme" },
      { valeur: "🔃", mots: "symbole signe flèche forme" },
      { valeur: "➕", mots: "symbole signe flèche forme" },
      { valeur: "➖", mots: "symbole signe flèche forme" },
      { valeur: "➗", mots: "symbole signe flèche forme" },
      { valeur: "✖️", mots: "symbole signe flèche forme" },
      { valeur: "♾️", mots: "symbole signe flèche forme" },
      { valeur: "💲", mots: "symbole signe flèche forme" },
      { valeur: "™️", mots: "symbole signe flèche forme" },
      { valeur: "©️", mots: "symbole signe flèche forme" },
      { valeur: "®️", mots: "symbole signe flèche forme" },
      { valeur: "〰️", mots: "symbole signe flèche forme" },
      { valeur: "➰", mots: "symbole signe flèche forme" },
      { valeur: "➿", mots: "symbole signe flèche forme" },
      { valeur: "🔚", mots: "symbole signe flèche forme" },
      { valeur: "🔙", mots: "symbole signe flèche forme" },
      { valeur: "🔛", mots: "symbole signe flèche forme" },
      { valeur: "🔝", mots: "symbole signe flèche forme" },
      { valeur: "🔜", mots: "symbole signe flèche forme" },
      { valeur: "✔️", mots: "symbole signe flèche forme" },
      { valeur: "☑️", mots: "symbole signe flèche forme" },
      { valeur: "🔘", mots: "symbole signe flèche forme" },
      { valeur: "🔴", mots: "symbole signe flèche forme" },
      { valeur: "🟠", mots: "symbole signe flèche forme" },
      { valeur: "🟡", mots: "symbole signe flèche forme" },
      { valeur: "🟢", mots: "symbole signe flèche forme" },
      { valeur: "🔵", mots: "symbole signe flèche forme" },
      { valeur: "🟣", mots: "symbole signe flèche forme" },
      { valeur: "⚫", mots: "symbole signe flèche forme" },
      { valeur: "⚪", mots: "symbole signe flèche forme" },
      { valeur: "🟤", mots: "symbole signe flèche forme" },
      { valeur: "🔺", mots: "symbole signe flèche forme" },
      { valeur: "🔻", mots: "symbole signe flèche forme" },
      { valeur: "🔸", mots: "symbole signe flèche forme" },
      { valeur: "🔷", mots: "symbole signe flèche forme" },
      { valeur: "🔶", mots: "symbole signe flèche forme" },
      { valeur: "🔹", mots: "symbole signe flèche forme" },
      { valeur: "🔳", mots: "symbole signe flèche forme" },
      { valeur: "🔲", mots: "symbole signe flèche forme" },
      { valeur: "🟥", mots: "symbole signe flèche forme" },
      { valeur: "🟧", mots: "symbole signe flèche forme" },
      { valeur: "🟨", mots: "symbole signe flèche forme" },
      { valeur: "🟩", mots: "symbole signe flèche forme" },
      { valeur: "🟦", mots: "symbole signe flèche forme" },
      { valeur: "🟪", mots: "symbole signe flèche forme" },
      { valeur: "⬛", mots: "symbole signe flèche forme" },
      { valeur: "⬜", mots: "symbole signe flèche forme" },
      { valeur: "🟫", mots: "symbole signe flèche forme" },
      { valeur: "🔈", mots: "symbole signe flèche forme" },
      { valeur: "🔇", mots: "symbole signe flèche forme" },
      { valeur: "🔉", mots: "symbole signe flèche forme" },
      { valeur: "🔊", mots: "symbole signe flèche forme" },
      { valeur: "🔔", mots: "symbole signe flèche forme" },
      { valeur: "🔕", mots: "symbole signe flèche forme" },
      { valeur: "📣", mots: "symbole signe flèche forme" },
      { valeur: "📢", mots: "symbole signe flèche forme" },
      { valeur: "💬", mots: "symbole signe flèche forme" },
      { valeur: "💭", mots: "symbole signe flèche forme" },
      { valeur: "🗯️", mots: "symbole signe flèche forme" },
      { valeur: "♠️", mots: "symbole signe flèche forme" },
      { valeur: "♣️", mots: "symbole signe flèche forme" },
      { valeur: "♥️", mots: "symbole signe flèche forme" },
      { valeur: "♦️", mots: "symbole signe flèche forme" },
      { valeur: "🃏", mots: "symbole signe flèche forme" },
    ],
  },
  {
    nom: "Drapeaux",
    entrees: [
      { valeur: "🏁", mots: "drapeau pays" },
      { valeur: "🚩", mots: "drapeau pays" },
      { valeur: "🎌", mots: "drapeau pays" },
      { valeur: "🏴", mots: "drapeau pays" },
      { valeur: "🏳️", mots: "drapeau pays" },
    ],
  },
];

const ICONES: ReadonlyArray<{ readonly nom: string; readonly Composant: typeof StarIcon }> = [
  { nom: "étoile favori star", Composant: StarIcon },
  { nom: "signet marque bookmark", Composant: BookmarkIcon },
  { nom: "coeur favori heart", Composant: HeartIcon },
  { nom: "drapeau flag repère", Composant: FlagIcon },
  { nom: "éclair rapide zap", Composant: ZapIcon },
  { nom: "flamme feu chaud", Composant: FlameIcon },
  { nom: "étincelles magie ia", Composant: SparklesIcon },
  { nom: "cloche alerte notif", Composant: BellIcon },
  { nom: "idée ampoule", Composant: LightbulbIcon },
  { nom: "palette design couleur", Composant: PaletteIcon },
  { nom: "plume dessin design", Composant: PenToolIcon },
  { nom: "calques espaces", Composant: LayersIcon },
  { nom: "base données db", Composant: DatabaseIcon },
  { nom: "processeur cpu perf", Composant: CpuIcon },
  { nom: "code dev", Composant: CodeIcon },
  { nom: "terminal shell", Composant: TerminalIcon },
  { nom: "bug débogage", Composant: BugIcon },
  { nom: "clé outil réglage", Composant: WrenchIcon },
  { nom: "dossier fichiers", Composant: FolderIcon },
  { nom: "boîte paquet", Composant: BoxIcon },
  { nom: "mallette travail", Composant: BriefcaseIcon },
  { nom: "calendrier date", Composant: CalendarIcon },
  { nom: "courrier mail", Composant: MailIcon },
  { nom: "monde global web", Composant: GlobeIcon },
  { nom: "boussole cap", Composant: CompassIcon },
  { nom: "carte plan", Composant: MapIcon },
  { nom: "maison accueil", Composant: HouseIcon },
  { nom: "personnes équipe", Composant: UsersIcon },
  { nom: "bouclier sécurité", Composant: ShieldIcon },
  { nom: "fusée lancement", Composant: RocketIcon },
  { nom: "croissance stats", Composant: TrendingUpIcon },
  { nom: "mégaphone annonce", Composant: MegaphoneIcon },
  { nom: "musique audio", Composant: MusicIcon },
  { nom: "vidéo film", Composant: VideoIcon },
  { nom: "image photo", Composant: ImageIcon },
  { nom: "appareil photo", Composant: CameraIcon },
  { nom: "jeu manette", Composant: GamepadIcon },
  { nom: "café pause", Composant: CoffeeIcon },
  { nom: "nuage cloud", Composant: CloudIcon },
  { nom: "feuille nature", Composant: LeafIcon },
  { nom: "soleil clair jour", Composant: SunIcon },
  { nom: "lune nuit sombre", Composant: MoonIcon },
  { nom: "camion livraison", Composant: TruckIcon },
  { nom: "baguette magie", Composant: WandIcon },
];

/** Le nom d'une icône lucide, préfixé pour le distinguer d'un emoji. */
export const ICON_PREFIX = "icon:";

export function estIconeLucide(valeur: string): boolean {
  return valeur.startsWith(ICON_PREFIX);
}

/** Rend l'icône d'un espace, qu'elle soit emoji ou icône lucide. */
export function SpaceIcon({ valeur, className }: { valeur: string; className?: string }) {
  if (!estIconeLucide(valeur)) {
    return <span className={cn("leading-none", className)}>{valeur}</span>;
  }
  const nom = valeur.slice(ICON_PREFIX.length);
  const trouve = ICONES.find((entree) => entree.nom === nom);
  const Composant = trouve?.Composant ?? StarIcon;
  return <Composant className={cn("size-4", className)} />;
}

export function SpaceIconPicker({
  valeur,
  onChange,
}: {
  readonly valeur: string;
  readonly onChange: (valeur: string) => void;
}) {
  const [onglet, setOnglet] = useState<"emoji" | "icone">("emoji");
  const [recherche, setRecherche] = useState("");
  const requete = recherche.trim().toLowerCase();

  const emojisFiltres = useMemo(() => {
    if (requete === "") return EMOJI_CATEGORIES;
    return EMOJI_CATEGORIES.map((categorie) => ({
      nom: categorie.nom,
      entrees: categorie.entrees.filter((entree) => entree.mots.includes(requete)),
    })).filter((categorie) => categorie.entrees.length > 0);
  }, [requete]);

  const iconesFiltrees = useMemo(
    () => (requete === "" ? ICONES : ICONES.filter((icone) => icone.nom.includes(requete))),
    [requete],
  );

  return (
    <div className="flex w-[320px] flex-col">
      <div className="flex items-center gap-1 px-3 pt-3">
        {(["emoji", "icone"] as const).map((cle) => (
          <button
            key={cle}
            type="button"
            onClick={() => setOnglet(cle)}
            className={cn(
              "cursor-pointer rounded-md px-2.5 py-1 text-[12px] font-medium transition-colors",
              onglet === cle
                ? "bg-primary text-primary-foreground"
                : "text-muted-foreground hover:bg-accent/60",
            )}
          >
            {cle === "emoji" ? "Emoji" : "Icône"}
          </button>
        ))}
      </div>
      <div className="relative px-3 pt-2">
        <SearchIcon className="pointer-events-none absolute left-5 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground/60" />
        <input
          value={recherche}
          onChange={(event) => setRecherche(event.currentTarget.value)}
          placeholder="Rechercher"
          className="h-8 w-full rounded-lg border border-border/60 bg-transparent pl-7 pr-2 text-[13px] outline-none focus:ring-2 focus:ring-ring"
        />
      </div>
      <div className="max-h-64 overflow-y-auto px-3 pb-3 pt-2">
        {onglet === "emoji" ? (
          emojisFiltres.length === 0 ? (
            <p className="py-6 text-center text-[12px] text-muted-foreground/70">
              Rien pour « {recherche} ».
            </p>
          ) : (
            emojisFiltres.map((categorie) => (
              <div key={categorie.nom} className="pb-2">
                <p className="pb-1 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground/60">
                  {categorie.nom}
                </p>
                <div className="grid grid-cols-8 gap-0.5">
                  {categorie.entrees.map((entree) => (
                    <button
                      key={entree.valeur}
                      type="button"
                      aria-label={entree.mots.split(" ")[0]}
                      onClick={() => onChange(entree.valeur)}
                      className={cn(
                        "flex aspect-square cursor-pointer items-center justify-center rounded-md text-[17px] transition-colors",
                        valeur === entree.valeur ? "bg-accent ring-1 ring-ring" : "hover:bg-accent/60",
                      )}
                    >
                      {entree.valeur}
                    </button>
                  ))}
                </div>
              </div>
            ))
          )
        ) : iconesFiltrees.length === 0 ? (
          <p className="py-6 text-center text-[12px] text-muted-foreground/70">
            Rien pour « {recherche} ».
          </p>
        ) : (
          <div className="grid grid-cols-8 gap-0.5">
            {iconesFiltrees.map(({ nom, Composant }) => {
              const cle = `${ICON_PREFIX}${nom}`;
              return (
                <button
                  key={nom}
                  type="button"
                  aria-label={nom.split(" ")[0]}
                  onClick={() => onChange(cle)}
                  className={cn(
                    "flex aspect-square cursor-pointer items-center justify-center rounded-md transition-colors",
                    valeur === cle ? "bg-accent ring-1 ring-ring" : "hover:bg-accent/60",
                  )}
                >
                  <Composant className="size-4" />
                </button>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
